export const MenuItemForm = [
    {
        title:"Menu Item ID",
        field:"ItemID",
        type:"",
        data:"",
        readOnly:true,
        placeholder:"This value is autogenerated"
    },
    {
        title:"Category",
        field:"CategoryID",
        type:"select",
        data:"",
        required:true
    },
   {
        title:"Item Name",
        field:"ItemName",
        type:"text",
        data:"",
        required:true
    },
    {
        title:"Description",
        field:"Description",
        type:"textarea",
        data:""
    },
    {
        title:"Price",
        field:"Price",
        type:"number",
        data:"",
        // required:true
    },
    {
        title:"Options",
        field:"Options",
        type:"array",
        arrayFields:[
            {title:"Option Name",field:"name",type:"text",data:""},
            {title:"Option Price",field:"price",type:"number",data:""},
        ],   
    },
    {
        title:"Image URL",
        field:"ImageURL",
        type:"text",
        data:""
    },
    {
        title:"Availability",
        field:"IsAvailable",
        type:"select",
        data:"",
        dropdownOptions:[
            {value:1,label:"Yes"},
            {value:0,label:"No"}],
    },
    {
        title:"Spice Level",
        field:"SpiceLevel",
        type:"slider",
        min:0,max:5,set:1,data:1
    },
    // {
    //     title: "Password",
    //     field: "password",
    //     type: "password"
    // },
]

export const MenuCategoriesForm = [
    {
        title:"Category ID",
        field:"CategoryID",
        type:"",
        data:"",
        readOnly: true,
        placeholder:"This value is autogenerated"
    },
    {
        title:"Category Name",
        field:"CategoryName",
        type:"text",
        data:""
    },
    {
        title:"Menu Type ",
        field:"MenuTypeID",
        type:"select",
        data:""
    },
    // {
    //     title: "Password",
    //     field: "password",
    //     type: "password"
    // },
]

export const MenuTypesForm = [
    {title:"Type ID",field:"MenuTypeID",type:"",data:"",readOnly:true,placeholder:"This value is autogenerated"},
    {title:"Type Name",field:"MenuTypeName",type:"text",data:""},
    // {title: "Password",field: "password",type: "password"},

]